// generated by gocipe 98bee01dcbcfef2fa8be1efb59ffb2d095d1ca8b8d0200a0c99f31ad111a69db; DO NOT EDIT

package citizen

import (
	"time"

	"github.com/fluxynet/gocipe-example/models/country"
)

// Citizen A human being belonging to a country
type Citizen struct {
	ID         *string          `json:"id"`
	Surname    *string          `json:""`
	OtherNames *string          `json:""`
	Gender     *string          `json:""`
	DOB        *time.Time       `json:""`
	Country    *country.Country `json:""`
}

// New returns an instance of Citizen
func New() *Citizen {
	return &Citizen{
		ID:         new(string),
		Surname:    new(string),
		OtherNames: new(string),
		Gender:     new(string),
		DOB:        new(time.Time),
		Country:    new(country.Country),
	}
}
