// generated by gocipe 2cdecd62f8cc1e3e1b51a96e61f1519e5d31bc3eb806037239eeb7707acf58b5; DO NOT EDIT

package country

import (
	"github.com/fluxynet/gocipe-example/models/capital"
	"github.com/fluxynet/gocipe-example/models/tag"
)

// Country A country
type Country struct {
	ID        *string          `json:"id"`
	Name      *string          `json:"name"`
	Continent *string          `json:""`
	Capital   *capital.Capital `json:"capital"`
	Citizens  []string         `json:""`
	Tags      []tag.Tag        `json:""`
}

// New returns an instance of Country
func New() *Country {
	return &Country{
		ID:        new(string),
		Name:      new(string),
		Continent: new(string),
		Capital:   new(capital.Capital),
	}
}
