// generated by gocipe fde8287dc8147e321eb245af512f5e1d059b75b9c464933b1ceb87a401fd8de6; DO NOT EDIT

package country

import (
	"github.com/fluxynet/gocipe-example/models/capital"
	"github.com/fluxynet/gocipe-example/models/tag"
)

// Country A country
type Country struct {
	ID        *string          `json:"id"`
	Name      *string          `json:"name"`
	Continent *string          `json:"continent"`
	Capital   *capital.Capital `json:"capital"`
	Citizen   []string         `json:"citizen"`
	Tags      []tag.Tag        `json:"tags"`
}

// New returns an instance of Country
func New() *Country {
	return &Country{
		ID:        new(string),
		Name:      new(string),
		Continent: new(string),
	}
}
