// generated by gocipe 2684eeb0295ee5f2f4177b7c406ae5c8553e74d3b44b524a3eeb29e37d1363f0; DO NOT EDIT

package country

import (
	"github.com/fluxynet/gocipe-example/models/capital"
	"github.com/fluxynet/gocipe-example/models/tag"
)

// Country A country
type Country struct {
	ID        *string          `json:"id"`
	Name      *string          `json:"name"`
	Continent *string          `json:"continent"`
	Capital   *capital.Capital `json:"capital"`
	Citizens  []string         `json:"citizens"`
	Tags      []tag.Tag        `json:"tags"`
}

// New returns an instance of Country
func New() *Country {
	return &Country{
		ID:        new(string),
		Name:      new(string),
		Continent: new(string),
	}
}
