// generated by gocipe 2684eeb0295ee5f2f4177b7c406ae5c8553e74d3b44b524a3eeb29e37d1363f0; DO NOT EDIT

package tag

// Tag Tags can be used to categories countries
type Tag struct {
	ID        *string  `json:"id"`
	Name      *string  `json:"name"`
	Countries []string `json:"countries"`
}

// New returns an instance of Tag
func New() *Tag {
	return &Tag{
		ID:   new(string),
		Name: new(string),
	}
}
