// generated by gocipe fde8287dc8147e321eb245af512f5e1d059b75b9c464933b1ceb87a401fd8de6; DO NOT EDIT

package tag

// Tag Tags can be used to categories countries
type Tag struct {
	ID        *string  `json:"id"`
	Name      *string  `json:"name"`
	Countries []string `json:"countries"`
}

// New returns an instance of Tag
func New() *Tag {
	return &Tag{
		ID:   new(string),
		Name: new(string),
	}
}
