-- generated by gocipe 2cdecd62f8cc1e3e1b51a96e61f1519e5d31bc3eb806037239eeb7707acf58b5; DO NOT EDIT

DROP TABLE IF EXISTS capitals;

CREATE TABLE capitals (
	"id" CHAR(36),
	"Capital" string NOT NULL,
	
	PRIMARY KEY ("id")
);

