-- generated by gocipe 02fef3d117f1029d4142b6b7ae2d1ea6f313fd8a2f44e25333775a308c8afb37; DO NOT EDIT

DROP TABLE IF EXISTS tags;

CREATE TABLE tags (
	"id" CHAR(36),
	"name" VARCHAR(255) NOT NULL,
	
	PRIMARY KEY ("id")
);


DROP TABLE IF EXISTS countries_tags;

CREATE TABLE countries_tags (
	"tags_id" CHAR(36) NOT NULL,
	"countries_id" CHAR(36) NOT NULL
);
