-- generated by gocipe 2684eeb0295ee5f2f4177b7c406ae5c8553e74d3b44b524a3eeb29e37d1363f0; DO NOT EDIT

DROP TABLE IF EXISTS ;

CREATE TABLE  (
	"id" CHAR(36),
	"surname" VARCHAR(255) NOT NULL,
	"othernames" VARCHAR(255) NOT NULL,
	"gender" CHAR(1) NOT NULL,
	"dob" DATE NOT NULL,
	
	PRIMARY KEY ("id")
);

