-- generated by gocipe 02fef3d117f1029d4142b6b7ae2d1ea6f313fd8a2f44e25333775a308c8afb37; DO NOT EDIT

DROP TABLE IF EXISTS countries;

CREATE TABLE countries (
	"id" CHAR(36),
	"name" VARCHAR(255) NOT NULL,
	"continent" VARCHAR(255) NOT NULL,
	
	PRIMARY KEY ("id")
);

