-- generated by gocipe 98bee01dcbcfef2fa8be1efb59ffb2d095d1ca8b8d0200a0c99f31ad111a69db; DO NOT EDIT

DROP TABLE IF EXISTS ;

CREATE TABLE  (
	"id" CHAR(36),
	"surname" VARCHAR(255) NOT NULL,
	"othernames" VARCHAR(255) NOT NULL,
	"gender" CHAR(1) NOT NULL,
	"dob" DATE NOT NULL,
	
	PRIMARY KEY ("id")
);

