// generated by gocipe 2cdecd62f8cc1e3e1b51a96e61f1519e5d31bc3eb806037239eeb7707acf58b5; DO NOT EDIT

package capital

// Capital Capital city of a country
type Capital struct {
	ID      *string `json:"id"`
	Capital *string `json:""`
	Country *string `json:""`
}

// New returns an instance of Capital
func New() *Capital {
	return &Capital{
		ID:      new(string),
		Capital: new(string),
		Country: new(string),
	}
}
