// generated by gocipe 2684eeb0295ee5f2f4177b7c406ae5c8553e74d3b44b524a3eeb29e37d1363f0; DO NOT EDIT

package capital

// Capital Capital city of a country
type Capital struct {
	ID      *string `json:"id"`
	Capital *string `json:"capital"`
	Country *string `json:"country"`
}

// New returns an instance of Capital
func New() *Capital {
	return &Capital{
		ID:      new(string),
		Capital: new(string),
	}
}
