// generated by gocipe fde8287dc8147e321eb245af512f5e1d059b75b9c464933b1ceb87a401fd8de6; DO NOT EDIT

package capital

// Capital Capital city of a country
type Capital struct {
	ID      *string `json:"id"`
	Capital *string `json:"capital"`
	Country *string `json:"country"`
}

// New returns an instance of Capital
func New() *Capital {
	return &Capital{
		ID:      new(string),
		Capital: new(string),
	}
}
