// generated by gocipe 02fef3d117f1029d4142b6b7ae2d1ea6f313fd8a2f44e25333775a308c8afb37; DO NOT EDIT

package models

import (
	"context"
	"database/sql"
	"strconv"
	"strings"

	"github.com/fluxynet/gocipe-example/util"
	"github.com/gobuffalo/uuid"
)

// Get returns a single Capital from database by primary key
func (repo CapitalRepository) Get(ctx context.Context, id string) (Capital, error) {
	var (
		rows   *sql.Rows
		err    error
		entity Capital
	)

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	rows, err = repo.db.Query("SELECT id, Capital FROM capitals WHERE id = $1 ORDER BY id ASC", id)
	if err != nil {
		return entity, err
	}

	defer rows.Close()
	if rows.Next() {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		err = rows.Scan(&entity.ID, &entity.Capital)
		if err != nil {
			return entity, err
		}

	}

	return entity, nil
}

// List returns a slice containing Capital records
func (repo CapitalRepository) List(ctx context.Context, filters []ListFilter, offset, limit int) ([]Capital, error) {
	var (
		list     []Capital
		segments []string
		values   []interface{}
		err      error
		rows     *sql.Rows
	)

	query := "SELECT id, Capital FROM capitals"

	if err = util.CheckContext(ctx); err != nil {
		return nil, err
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	if limit > -1 {
		query += " LIMIT " + strconv.Itoa(limit)
	}

	if offset > -1 {
		query += " OFFSET " + strconv.Itoa(limit)
	}

	query += " ORDER BY id ASC"

	rows, err = repo.db.Query(query, values...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {
		if err = util.CheckContext(ctx); err != nil {
			return nil, err
		}

		var entity Capital

		err = rows.Scan(entity.ID, &entity.Capital)
		if err != nil {
			return nil, err
		}

		list = append(list, entity)
	}

	return list, nil
}

// Delete deletes a Capital record from database and sets id to nil
func (repo CapitalRepository) Delete(ctx context.Context, entity Capital, tx *sql.Tx, autocommit bool) (Capital, error) {
	var (
		err  error
		stmt *sql.Stmt
	)
	id := entity.ID

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	stmt, err = tx.Prepare("DELETE FROM capitals WHERE id = $1")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	_, err = stmt.Exec(id)
	if err == nil {
		entity.ID = ""
	} else {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, nil
}

// DeleteMany deletes many Capital records from database using filter
func (repo CapitalRepository) DeleteMany(ctx context.Context, filters []ListFilter, tx *sql.Tx, autocommit bool) error {
	var (
		err      error
		stmt     *sql.Stmt
		segments []string
		values   []interface{}
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return err
		}
	}

	query := "DELETE FROM capitals"

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	stmt, err = repo.db.Prepare(query)
	if err != nil {
		return err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	_, err = stmt.Exec(values...)
	if err != nil {
		tx.Rollback()
		return err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	if autocommit {
		err = tx.Commit()
	}

	return err
}

// Save either inserts or updates a Capital record based on whether or not id is nil
func (repo CapitalRepository) Save(ctx context.Context, entity Capital, tx *sql.Tx, autocommit bool) (Capital, error) {
	if entity.ID == "" {
		return CapitalRepo.Insert(ctx, entity, tx, autocommit)
	}
	return CapitalRepo.Update(ctx, entity, tx, autocommit)
}

// Insert performs an SQL insert for Capital record and update instance with inserted id.
func (repo CapitalRepository) Insert(ctx context.Context, entity Capital, tx *sql.Tx, autocommit bool) (Capital, error) {
	var (
		id   string
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	stmt, err = tx.Prepare("INSERT INTO capitals (id, Capital) VALUES ($1, $2)")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	idUUID, err := uuid.NewV4()

	if err == nil {
		id = idUUID.String()
	} else {
		tx.Rollback()
		return entity, err
	}
	entity.ID = id

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	_, err = stmt.Exec(entity.ID, entity.Capital)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, nil
}

// Update Will execute an SQLUpdate Statement for Capital in the database. Prefer using Save instead of Update directly.
func (repo CapitalRepository) Update(ctx context.Context, entity Capital, tx *sql.Tx, autocommit bool) (Capital, error) {
	var (
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	stmt, err = tx.Prepare("UPDATE capitals SET Capital = $1 WHERE id = $1")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}
	_, err = stmt.Exec(entity.Capital)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, err
}

// Merge performs an SQL merge for Capital record.
func (repo CapitalRepository) Merge(ctx context.Context, entity Capital, tx *sql.Tx, autocommit bool) (Capital, error) {
	var (
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	if entity.ID == "" {
		return CapitalRepo.Insert(ctx, entity, tx, autocommit)
	}

	stmt, err = tx.Prepare(`INSERT INTO capitals (id, Capital) VALUES ($1, $2) 
	ON CONFLICT (id) DO UPDATE SET Capital = $2`)
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}
	_, err = stmt.Exec(entity.ID, entity.Capital)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, err
}
