// generated by gocipe fde8287dc8147e321eb245af512f5e1d059b75b9c464933b1ceb87a401fd8de6; DO NOT EDIT

package models

//ListFilter represents a filter to apply during listing (crud)
type ListFilter struct {
	Field     string
	Operation string
	Value     interface{}
}
