// generated by gocipe 02fef3d117f1029d4142b6b7ae2d1ea6f313fd8a2f44e25333775a308c8afb37; DO NOT EDIT

package models

import (
	"context"
	"database/sql"
	"strconv"
	"strings"

	"github.com/fluxynet/gocipe-example/util"
	"github.com/gobuffalo/uuid"
)

// Get returns a single Tag from database by primary key
func (repo TagRepository) Get(ctx context.Context, id string) (Tag, error) {
	var (
		rows   *sql.Rows
		err    error
		entity Tag
	)

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	rows, err = repo.db.Query("SELECT id, name FROM tags WHERE id = $1 ORDER BY id ASC", id)
	if err != nil {
		return entity, err
	}

	defer rows.Close()
	if rows.Next() {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		err = rows.Scan(&entity.ID, &entity.Name)
		if err != nil {
			return entity, err
		}

	}

	return entity, nil
}

// List returns a slice containing Tag records
func (repo TagRepository) List(ctx context.Context, filters []ListFilter, offset, limit int) ([]Tag, error) {
	var (
		list     []Tag
		segments []string
		values   []interface{}
		err      error
		rows     *sql.Rows
	)

	query := "SELECT id, name FROM tags"

	if err = util.CheckContext(ctx); err != nil {
		return nil, err
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	if limit > -1 {
		query += " LIMIT " + strconv.Itoa(limit)
	}

	if offset > -1 {
		query += " OFFSET " + strconv.Itoa(limit)
	}

	query += " ORDER BY id ASC"

	rows, err = repo.db.Query(query, values...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	for rows.Next() {
		if err = util.CheckContext(ctx); err != nil {
			return nil, err
		}

		var entity Tag

		err = rows.Scan(entity.ID, &entity.Name)
		if err != nil {
			return nil, err
		}

		list = append(list, entity)
	}

	return list, nil
}

// Delete deletes a Tag record from database and sets id to nil
func (repo TagRepository) Delete(ctx context.Context, entity Tag, tx *sql.Tx, autocommit bool) (Tag, error) {
	var (
		err  error
		stmt *sql.Stmt
	)
	id := entity.ID

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	stmt, err = tx.Prepare("DELETE FROM tags WHERE id = $1")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	_, err = stmt.Exec(id)
	if err == nil {
		entity.ID = ""
	} else {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, nil
}

// DeleteMany deletes many Tag records from database using filter
func (repo TagRepository) DeleteMany(ctx context.Context, filters []ListFilter, tx *sql.Tx, autocommit bool) error {
	var (
		err      error
		stmt     *sql.Stmt
		segments []string
		values   []interface{}
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return err
		}
	}

	query := "DELETE FROM tags"

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	for i, filter := range filters {
		segments = append(segments, filter.Field+" "+filter.Operation+" $"+strconv.Itoa(i+1))
		values = append(values, filter.Value)
	}

	if len(segments) != 0 {
		query += " WHERE " + strings.Join(segments, " AND ")
	}

	stmt, err = repo.db.Prepare(query)
	if err != nil {
		return err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	_, err = stmt.Exec(values...)
	if err != nil {
		tx.Rollback()
		return err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return err
	}

	if autocommit {
		err = tx.Commit()
	}

	return err
}

// Save either inserts or updates a Tag record based on whether or not id is nil
func (repo TagRepository) Save(ctx context.Context, entity Tag, tx *sql.Tx, autocommit bool) (Tag, error) {
	if entity.ID == "" {
		return TagRepo.Insert(ctx, entity, tx, autocommit)
	}
	return TagRepo.Update(ctx, entity, tx, autocommit)
}

// Insert performs an SQL insert for Tag record and update instance with inserted id.
func (repo TagRepository) Insert(ctx context.Context, entity Tag, tx *sql.Tx, autocommit bool) (Tag, error) {
	var (
		id   string
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	stmt, err = tx.Prepare("INSERT INTO tags (id, name) VALUES ($1, $2)")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	idUUID, err := uuid.NewV4()

	if err == nil {
		id = idUUID.String()
	} else {
		tx.Rollback()
		return entity, err
	}
	entity.ID = id

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	_, err = stmt.Exec(entity.ID, entity.Name)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, nil
}

// Update Will execute an SQLUpdate Statement for Tag in the database. Prefer using Save instead of Update directly.
func (repo TagRepository) Update(ctx context.Context, entity Tag, tx *sql.Tx, autocommit bool) (Tag, error) {
	var (
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	stmt, err = tx.Prepare("UPDATE tags SET name = $1 WHERE id = $1")
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}
	_, err = stmt.Exec(entity.Name)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		tx.Rollback()
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, err
}

// Merge performs an SQL merge for Tag record.
func (repo TagRepository) Merge(ctx context.Context, entity Tag, tx *sql.Tx, autocommit bool) (Tag, error) {
	var (
		err  error
		stmt *sql.Stmt
	)

	if tx == nil {
		if err = util.CheckContext(ctx); err != nil {
			return entity, err
		}

		tx, err = repo.db.Begin()
		if err != nil {
			return entity, err
		}
	}

	if entity.ID == "" {
		return TagRepo.Insert(ctx, entity, tx, autocommit)
	}

	stmt, err = tx.Prepare(`INSERT INTO tags (id, name) VALUES ($1, $2) 
	ON CONFLICT (id) DO UPDATE SET name = $2`)
	if err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}
	_, err = stmt.Exec(entity.ID, entity.Name)
	if err != nil {
		tx.Rollback()
		return entity, err
	}

	if err = util.CheckContext(ctx); err != nil {
		return entity, err
	}

	if autocommit {
		err = tx.Commit()
	}

	return entity, err
}

// LoadCountries is a helper function to load related Countries entities
func (repo TagRepository) LoadCountries(ctx context.Context, entities ...Tag) error {
	var (
		err         error
		placeholder string
		values      []interface{}
		indices     = make(map[string][]*Tag)
	)

	if err = util.CheckContext(ctx); err != nil {
		return err
	}

	c := 1
	for _, entity := range entities {
		placeholder += "$" + strconv.Itoa(c) + ","
		indices[entity.ID] = append(indices[entity.ID], &entity)
		values = append(values, entity.ID)
		c++
	}
	placeholder = strings.TrimRight(placeholder, ",")

	rows, err := repo.db.Query("SELECT tag_id, country_id FROM countries_tags WHERE tag_id IN ("+placeholder+")", values...)
	if err != nil {
		return err
	}

	if err = util.CheckContext(ctx); err != nil {
		return err
	}

	for rows.Next() {
		var (
			thisID string
			thatID string
		)
		err = rows.Scan(&thisID, &thatID)
		if err != nil {
			return err
		}

		for _, ent := range indices[thisID] {
			ent.Countries = append(ent.Countries, thatID)
		}

		if err = util.CheckContext(ctx); err != nil {
			return err
		}
	}

	return nil
}
